# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true

notifications:   
  email:   
    on_success: change   
    on_failure: change
